version: "3.0"
services:
  nginx:
    build: .
    container_name: howoldis
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app
      - ./Makefile:/Makefile
      - ./tests:/tests

